spring:
  application:
    name: healthcare-qr-sharing
  
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/healthcare_qr}
    username: ${DB_USERNAME:healthcare_user}
    password: ${DB_PASSWORD:healthcare_pass}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_ISSUER_URI:https://your-oauth-provider.com}
          
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Custom Application Properties
healthcare:
  security:
    encryption:
      key: ${ENCRYPTION_KEY:your-256-bit-encryption-key}
      algorithm: AES/GCM/NoPadding
    jwt:
      secret: ${JWT_SECRET:your-jwt-secret}
      expiration: 3600000 # 1 hour
    qr:
      expiration-minutes: 15
      max-data-types: 10
  
  fhir:
    server:
      base-url: ${FHIR_SERVER_URL:http://localhost:8080/fhir}
      validation: true
    
  audit:
    enabled: true
    retention-days: 2555 # 7 years for HIPAA compliance

server:
  port: 8080
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: ${SSL_KEYSTORE:classpath:keystore.p12}
    key-store-password: ${SSL_KEYSTORE_PASSWORD:changeit}
    key-store-type: PKCS12

logging:
  level:
    com.healthcare: DEBUG
    org.springframework.security: DEBUG
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/healthcare-qr.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized