services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=postgres
      - DB_USERNAME={POSTGRES_USER}
      - DB_PASSWORD={POSTGRES_PASSWORD}
      - ENCRYPTION_KEY={ENCRYPTION_KEY}
      - JWT_SECRET={JWT_SECRET}
    depends_on:
      - postgres
      - redis
    networks:
      - healthcare-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: healthcare_qr
      POSTGRES_USER: HealthCareForAllAdmin
      POSTGRES_PASSWORD: H3althcar3QrD3vAdm1n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - healthcare-network

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - healthcare-network

volumes:
  postgres_data:
  redis_data:

networks:
  healthcare-network:
    driver: bridge